### PR TITLE
start adding [new] scipy2022 tutorial content

### PR DESCRIPTION
**Pull request by JessicaS11**
Populated the scipy2022 workshop content by adding url links in the table of contents to that section. For new content, I created notebooks with high level framing for us to fill in content.

### CODE REVIEW

**Comment by JessicaS11** [comment]
I'll note that this successfully builds for me locally...

**Comment by dcherian** [comment]
I had some comments but then just implemented them to save time. Please feel free to revert any of the commits if you don't  like it.

1. Rename "scipy-tutorial" folder to "fundamentals"
2. Moved dask material to under the "advanced" folder.
3. Movoed the "thinking like xarray" material to "intermediate"

Followups:
- I think we should delete "intro to dask" notebook and link to dask docs instead.

**Review by dcherian — APPROVED** [review]

**Review by scottyhq — APPROVED** [review]
I like it! +1 to moving to official tutorials and user guides in other repositories (dask). Also having an overview/quickstart/whirlwind tour up top. I say we merge this and follow in separate PRs

**Comment by dcherian** [comment]
Thanks @JessicaS11 Merging since this seems to be a blocker for other  work. We can  keep refining in future PRs

**Pull request merged**
