### PR TITLE
add computation tutorial

### PR DESCRIPTION
**Pull request by rabernat**

### CODE REVIEW

**Comment by rabernat** [comment]
So my notebook has a deliberate error, which is causing the CI to fail:
https://github.com/xarray-contrib/xarray-tutorial/pull/13/checks?check_run_id=762122971#step:6:256

How should I handle this? try / except?

My feeling is that it's useful to see an error message that arises from a common situation.

**Comment by keewis** [comment]
I think we'd probably need a way to somehow mark cells (using a cell magic?) such that the exception is caught but the stacktrace is still visible

**Comment by keewis** [comment]
you could try [expectexception](https://github.com/thedataincubator/expectexception)

**Comment by rabernat** [comment]
Good suggestion. expectexception worked. But travis-ci is still failing. Why do we need both?

**Comment by keewis** [comment]
not sure, but the travis failure is a network connection issue (rerunning should fix that)

**Comment by jhamman** [comment]
Yes, doctr doesn't support github actions (yet).

**Comment by rabernat** [comment]
> Yes, doctr doesn't support github actions (yet).

We don't need doctr. You can deploy directly to github pages without doctr using github actions.

Example: https://github.com/pangeo-gallery/pangeo-gallery/blob/master/.github/workflows/build-and-deploy.yml

**Comment by jhamman** [comment]
@rabernat - totally open to dropping doctr. You have a more experience in this area so I'm happy to let you take the lead here.

**Comment by rabernat** [comment]
I can't merge this myself. Could someone else please do it?

**Comment by dcherian** [comment]
Thanks ryan

**Pull request merged**
