### PR TITLE
Add sphinx-autocodelink & intersphinx_mapping

### PR DESCRIPTION
**Pull request by dcherian**
xref #82

This somewhat works.
- intersphinx to xarray doesn't work
- sphinx-codeautolink seems buggy and doesn't work in as many places it could (e.g. https://github.com/felix-hilden/sphinx-codeautolink/issues/109)

### CODE REVIEW

**Comment by zmoon** [comment]
> * intersphinx to xarray doesn't work

Just curious about this. Like ``{py:class}`xarray.Dataset` `` / ``{external+xarray:py:class}`xarray.Dataset` `` doesn't work? [Or using](https://myst-parser.readthedocs.io/en/latest/develop/_changelog.html?highlight=intersphinx#id28) `[title](ref)`? Does it work with the pydata docs URL?

**Comment by zmoon** [comment]
After a bit of investigation, seems like xarray isn't working because it doesn't have an xarray module doc reference? e.g. for NumPy `'numpy': 'https://numpy.org/doc/stable/reference/index.html#module-numpy'`. And Matplotlib `'numpy': 'https://numpy.org/doc/stable/reference/index.html#module-numpy'`, with `.. module:: matplotlib` on the home page [here](https://github.com/matplotlib/matplotlib/blob/c9bc943874f32eec64d21f5789406bc8e76c8fa6/doc/index.rst).

**Comment by dcherian** [comment]
Thanks for the conda lock tip.

I'm 50/50 on this PR. When it works, it's great. But I find myself hovering over things that just don't work. Like

```
ds = xr.Dataset(...)
```

will not link Dataset!

```
xr.Dataset
```

^ This supposedly will link though

**Comment by scottyhq** [comment]
gotcha. I'm fine leaving this in draft form and revisiting at some later date, or separate out just the intersphinx piece (maybe just for xarray?) and revisit the code block autolinking later?

**Comment by zmoon** [comment]
> When it works, it's great

When I was trying it I found that it only seemed to work for full build from clean, not partial builds, which is kind of annoying.

**Comment by felix-hilden** [comment]
Yooo thanks for trying autolink out, author here 👋 Did you encounter other bugs besides the one mentioned?

```python
ds = xr.DataSet(...)
```

should be linked in terms of the `xr.DataSet` part, but indeed felix-hilden/sphinx-codeautolink#109 will perhaps address the assignment target! Notebooks have been a pain point though, I wouldn't be surprised if there are things to iron out. Much appreciated!

**Comment by dcherian** [comment]
The following seems like it should be supported or is it https://github.com/felix-hilden/sphinx-codeautolink/issues/65?


image

Here `da` is a `DataArray`

So i'd expect 
1. `da` to link to https://docs.xarray.dev/en/latest/generated/xarray.DataArray.html 
2. `.resample` to link to https://docs.xarray.dev/en/latest/generated/xarray.DataArray.resample.html, (similarly for .isel, .plot)
3. and the `.mean` to https://docs.xarray.dev/en/latest/generated/xarray.core.resample.DataArrayResample.mean.html


https://sphinx-codeautolink.readthedocs.io/en/latest/examples.html#concatenating-examples and https://sphinx-codeautolink.readthedocs.io/en/latest/examples.html#concatenating-examples shows the behaviour I want.

**Comment by felix-hilden** [comment]
Yep, it should work as long as the type hints are available 👌 Getting `air` might be the culprit here if it's not working. At a quick glance I didn't find it in your code / documentation.

**Comment by dcherian** [comment]
It's the first cell in https://github.com/xarray-contrib/xarray-tutorial/blob/8f250e358af50998174ad08f311069bb044421d1/intermediate/01-high-level-computation-patterns.ipynb

**Comment by felix-hilden** [comment]
Right, but the reference documentation or type hinted importable location of "air" I meant!

**Comment by dcherian** [comment]
Oh I see the problem now. It comes from this mixin class but the return value is `Any` so that's useless for linking I guess.

https://github.com/pydata/xarray/blob/d0bfd00d41fd3a70b70f7f63b7f94f775da9be9c/xarray/core/common.py#L271

I can change the code to use `Dataset.__getitem__` instead.

**Comment by felix-hilden** [comment]
Yep most likely. Fair warning though, I don't think we provide any special support for `__getitem__`. You might be better off type hinting the variable instead. We override the target with type hints (test [here](https://github.com/felix-hilden/sphinx-codeautolink/blob/master/tests/parse/assign.py#L128) although it's a bit hard to read).

**Comment by dcherian** [comment]
image

Still no luck after explicit typing unfortunately

**Comment by felix-hilden** [comment]
Oh, that's unfortunate. `resample` should definitely be available judging by the documentation. I'll debug this later this week and get back to you.

**Comment by felix-hilden** [comment]
I found the culprit! The inventory and documentation entry for `DataArray` is `xarray.DataArray`, and rightly so of course since it's much more user-friendly than using the full import. The problem is that we use the fully qualified name of a class to determine the canonical location of a class to link items. This is done to avoid issues when bouncing around the library imports when resolving names to locations.

So linking `DataArray` correctly would require us to edit the module location by hand, much like I've done [here](https://github.com/felix-hilden/tekore/blob/master/src/tekore/__init__.py#L112). Maybe you don't want to go as far as to mark the underlying modules as private, but just modifying the attribute should suffice.

**Comment by dcherian** [comment]
Oh interesting. Thanks for tracking that down.

Would it be feasible to do this as a variable in `conf.py`? Say

```python
codeautolink_module_overrides = {
	"DataArray": "xarray",
	"Dataset": "xarray",
}
```

**Comment by felix-hilden** [comment]
I like the idea! Let's continue the discussion on the linked issue.

**Comment by scottyhq** [comment]
@dcherian I wanted to revive this one now that I have a previews working again and bumped all the package versions. 

To get methods like da.resample() and others to link correctly (e.g. https://xarray-contrib-xarray-tutorial-preview-pr-85.surge.sh/intermediate/01-high-level-computation-patterns.html). It sounds like we'd need to add a custom map file to this repository based on https://github.com/felix-hilden/sphinx-codeautolink/issues/131#issuecomment-1419496681 

So,,, options are 1: merge as-is with limited functionality (I'm happy with this), 2: add a custom map file, or 3: abandon adding this feature

**Comment by dcherian** [comment]
Merge away!

**Pull request merged**
