### PR TITLE
Edits to "Xarray and Dask"

### PR DESCRIPTION
**Pull request by yutik-nn**
changes minor points that might be causing confusion to the user (1. variable misnames 2. specifying the directory in the cluster was misleading )

### CODE REVIEW

**Comment by scottyhq** [comment]
great catch with the mismatched names in the exercise @yutik-nn !

> 2. specifying the directory in the cluster was misleading

I agree that `client = Client(local_directory='/tmp')` is unclear, it makes it seem like we might have data in that folder.

The reason for that setting was discussed here, and it's also good practice to use 'scratch spaces' for temporary files
https://github.com/xarray-contrib/xarray-tutorial/issues/75#issuecomment-1158050289 ,

Instead of removing `local_directory='/tmp'` what do you think of adding a sentence above saying something like "dask uses the current working directory for writing temporary files by default. We use the argument `local_directory='/tmp'` below to instead use a temporary scratch folder" ?

**Comment by yutik-nn** [comment]
Thank you for your comments @scottyhq !
The reasoning behind me removing `local_directory='/tmp'` altogether was that it appears  in many other tutorials so it seemed like an unnecessarily complicated thing to have a specified folder here, but I see your reasoning now. 
Yes, I think adding a sentence explaining it is a good suggestion!

**Comment by dcherian** [comment]
@yutik-nn did we decide that adding info on `persist` was a distraction?

**Comment by yutik-nn** [comment]
> @yutik-nn did we decide that adding info on `persist` was a distraction?

I did not do anything to the section yet, honestly. It seems to have appeared in edits because I removed some characters? But I did not touch it consciously. I added the sentence about the scratch directory only.

**Review by scottyhq — APPROVED** [review]

**Comment by dcherian** [comment]
Nice work! 🥳

**Comment by JessicaS11** [comment]
@yutik-nn @scottyhq @dcherian Based on this discussion, shouldn't the line of code have stayed as `client = Client(local_directory='/tmp')` rather than `client = Client()`?

**Comment by scottyhq** [comment]
whoops, i missed that! @yutik-nn would you mind a follow-up PR to add that back in?

**Pull request merged**
