### PR TITLE
Update links

### LINKED ISSUE #67: Fix broken links
Transferring from: https://github.com/xarray-contrib/xarray-tutorial/pull/59#issuecomment-1145133608

CI log here (under 'Check External Links' step) https://github.com/xarray-contrib/xarray-tutorial/runs/6817806572?check_suite_focus=true

### PR DESCRIPTION
**Pull request by zmoon**
* Update some links for redirects
* Update xarray docs URLs to use https://docs.xarray.dev/ instead of `http(s)://xarray.pydata.org/`
* Update the NOAA SST URL from https://www.ncdc.noaa.gov/data-access/marineocean-data/extended-reconstructed-sea-surface-temperature-ersst-v5 [^1] to https://www.ncei.noaa.gov/products/extended-reconstructed-sst
* Add `user-guide` to xarray docs URLs where needed [^2]

Fixes #67

[^1]: redirects to not-found page https://www.ncei.noaa.gov/products/marineocean-data/extended-reconstructed-sea-surface-temperature-ersst-v5
[^2]: fixing errors like this:  
  image
  Those links did work, I guess they just redirected without sending redirect code or something.

### CODE REVIEW

**Comment by zmoon** [comment]
This is the only one left

image

<https://docs.google.com/presentation/d/16CMY3g_OYr6fQplUZIDqVtG-SKZqsG8Ckwoj2oOqepU/edit#slide=id.g2b68f9254d_1_154>

I does work, but I guess link checker can't handle it since it is using js to select slide or something? Maybe could configure to ignore that one.

**Comment by dcherian** [comment]
> Or just remove the anchor part

Seems OK since we explicitly include the image.

**Comment by dcherian** [comment]
Thanks @zmoon ! great to see you contribute here

**Comment by zmoon** [comment]
Would you want to remove `continue-on-error: true` from that step in the workflow now that it passes?

**Comment by dcherian** [comment]
Sure that would be great!

**Pull request merged**
