### PR TITLE
Bump all packages and actions

### PR DESCRIPTION
**Pull request by scottyhq**
major changes: 

* python 3.11
* xarray 2023.5.0
* jupyterbook 0.15.2

### CODE REVIEW

**Comment by scottyhq** [comment]
All green! FYI In order to lock the environment for osx-64 I had to use conda 22.9 (https://github.com/conda/conda-lock/issues/408),,, seems like it'll be fixed for next release of conda.

**Review by lsetiawan — COMMENTED** [review]
This is great @scottyhq! Can you also specify the package version for `jupyter-book` and `xarray` in the `environment-unpinned.yml`? I know you have the more specific ones in `environment.yml` but for the sake of those that has the new Mac M1/M2 machines, I can't use those and have to use the unpinned yml file. So to ensure that we get the same versions, it's probably good to pin at least the xarray version and jupyter book to minimize headaches for participants in case the upstream package updates before July 😛 Thanks!

**Comment by scottyhq** [comment]
> for the sake of those that has the new Mac M1/M2 machines 

I thought in theory the lock for `-p osx-arm64` was for these fancy new machines :) 
https://github.com/xarray-contrib/xarray-tutorial/blob/3eadc8afa59e9704d6a4cf81726fe80f459bffca/conda/README.md?plain=1#L16

@lsetiawan from the `conda` folder can you try `conda-lock install -n xarray-tutorial` or `micromamba create -n xarray-tutorial -f conda-lock.yml` I definitely think we should push people towards a binderhub for the scipy tutorial to avoid these complications.

**Comment by lsetiawan** [comment]
Ah. I haven't used much of conda lock and it's Friday afternoon. I guess that's my issue 😉 Sounds good. I agree in pushing people towards binderhub. Thanks for the explanation 😄

**Review by lsetiawan — APPROVED** [review]

**Pull request merged**
