### PR TITLE
Redo Computation section

### LINKED ISSUE #61: Update apply_ufunc section
current uses some gsw thing that actually returns a DataArray now.

### LINKED ISSUE #62: Better description of intermediate grouphby, weighted etc objects
Fix here: https://tutorial.xarray.dev/scipy-tutorial/03_computation_with_xarray.html#weighted-reductions

Other material here: https://tutorial.xarray.dev/thinking-like-xarray/01-high-level-computation-patterns.html

### PR DESCRIPTION
**Pull request by dcherian**
- [x] Closes #61
- [x] Fixes the apply-ufunc section
- [x] Switches to using `tutorial.load_dataset("ersstv5")`
- [x] Split out rolling, coarsen
- [x] Update rolling, coarsen notebooks
- [x] Remove matplotlib return values
- [x] LIttle more on analogies between resampling and groupby objects
- [x] Fix #62 
- [x] update broadcasting material and use nicer image from "xarray online tutorial"
- [ ] update weighted material

One issue is that it makes sense to put alignment under computation. Thiis means we need to rename it to change the `02_` prefix to `03_`. It seems like we might want to avoid these prefixes?

I'll continue splitting up the groupby notebook into more subparts.

### CODE REVIEW

**Comment by dcherian** [comment]
OK This is ready for review!

I reworked the material quite a bit!

**Comment by scottyhq** [comment]
There is a lot here! I haven't looked it all over yet, but here are some notes, also happy to merge and come back to these as future improvements as it's looking great as is.

Could add additional learning goal briefly describing dataset analysis task:  “compute trends in sea surface temperature over the last X years”

BASIC COMPUTATION 
1. use `sst_kelvin.head(2)` or `hide-output` metadata tag for reduced scolling / repetitive outputs
2. applying functions -> remove “including numpy ufuncs”

? why do some functions return dataarrays and others numpy arrays (nan-to-num)

3. remove ‘mysterious’ :)

Reduction: apply a function that reduced the dimensionlity of our dataset, for example taking the mean sea surface temperature through time of our 3D data, we *reduce* time and are left with a 2D array.


COMPUTING WITH MULTIPLE OBJECTS
1. show html for arr1 and arr2 at the top 

2. `array1` is missing dimension `time` and `array2`…

3. only hide output of excercise cell

markers in join comparison plot
on ‘join plots’ would be nice to show <-  (left arrow markers for left array, and -> arrow marker for right array with big circle to show selected value)! 

GROUPED COMPUTATIONS
* ‘physically motivated’ -> ‘motivating example’

* remove `time_bnds` variable? or mention what it is

* ?ds.groupby
NOTE: the correct metadata tag is `output_scroll` with an underscore (wish they were consistently hyphens!)

* `hide-output` or head(2)? or scrolling output (months and years)

* “expects and returns” xarray objects

* Add a note on considering the original temporal sampling before the groupby (ds.time.dt.month), we quickly see we have 1 sample per month. So you probably would not want to groupby ds.time.dt.day (all measurements arbitrarily assigned the first day of month)

* clarify note:
“Note: resample only works with recognize datetime indexes (not ordinary python strings)”

* also compare data values `np.array_equal(grouped, resampled)`?

**Review by scottyhq — APPROVED** [review]

**Comment by dcherian** [comment]
Great comments Scott!

I've addressed them and will merge now.

**Comment by scottyhq** [comment]
Thanks for doing all the work on this @dcherian! I didn't know you can do `xr.set_options(display_expand_data=False)`, which is nice for the jupyterbook rendering

**Pull request merged**
