### PR TITLE
add action for spellcheck and linkcheck

### PR DESCRIPTION
**Pull request by scottyhq**
see https://github.com/codespell-project/codespell 

and https://jupyterbook.org/en/stable/advanced/html.html#check-external-links-in-your-book

### CODE REVIEW

**Comment by scottyhq** [comment]
Lots of broken links, can fix those in a follow up PR `https://xarray.pydata.org/en/latest/dask.html#map-blocks -> https://xarray.pydata.org/en/latest/user-guide/dask.html#map-blocks`

**Comment by max-sixty** [comment]
This is great!

Is there also a pre-commit hook for spelling? (I know for links, pre-commit.ci doesn't work because it doesn't have internet access)

**Comment by scottyhq** [comment]
> Is there also a pre-commit hook for spelling? 

Looks like there is! But I haven't used it. Should I add that as well or instead of the github action step? https://pre-commit.com/hooks.html

**Comment by max-sixty** [comment]
> Should I add that as well or instead of the github action step?

Personally I would vote to aggregate them in pre-commit, because it's really easy to run locally. But your call!

(Also fine to merge this now to avoid conflicts and then resolve after)

**Comment by max-sixty** [comment]
We could also add the link check to pre-commit, add `ci:\n  skip: [markdown-link-check]` to avoid it attempting in `ci`, but this is very refine-y, and the proposed code is already excellent.

**Comment by scottyhq** [comment]
I advocate for merging this as-is and adding to pre-commit later if desirable. While I agree it would be convenient, both of these checks can have lots of false positives and the linkchecking can hang with network failures. So they seem well suited to opt-in or PR-level checks. The jupyterbook linkchecker I think also deals with many more formats and markup (myst-markdown). 

It does look possible to setup both [opt-out](https://pre-commit.com/#temporarily-disabling-hooks) (SKIP=codespell git commit -m "foo" ) or [opt-in](https://pre-commit.com/#confining-hooks-to-run-at-certain-stages) (`pre-commit run --hook-stage manual codespell`)

**Comment by dcherian** [comment]
I agree ^. Also moving quickly is beneficial at the moment given the upcoming SciPy deadline.

**Comment by max-sixty** [comment]
Very much agree re merging! Thanks for doing that!

**Pull request merged**
