### PR TITLE
Add jupyterlab-myst

### LINKED ISSUE #115: test out jupyterlab-myst
https://github.com/executablebooks/jupyterlab-myst

This would allow us to use myst syntax for nice rendering in Jupyter Lab and the JupyterBook deployment.

 I see @scottyhq  has already opened an issue there :)

### PR DESCRIPTION
**Pull request by scottyhq**
closes #115

caveats:

* requires pinning to jupyterlab<4: https://github.com/executablebooks/jupyterlab-myst/issues/148)
* doesn't yet work with jupyterlite:  https://github.com/executablebooks/jupyterlab-myst/issues/132
* doesn't seem to work with vscode

### CODE REVIEW

**Review by lsetiawan — APPROVED** [review]
LGTM

**Comment by rowanc1** [comment]
@scottyhq, we just released `jupyterlab-myst v2.0.0` which supports jlab-v4, hope that removes a caveat!

**Comment by dcherian** [comment]
I think there is now support for JupyterLab 4.0 on the latest v2.0.0 release (https://github.com/executablebooks/jupyterlab-myst/pull/155)

**Comment by scottyhq** [comment]
i'll go ahead an merge and we can bump versions again next week!

**Pull request merged**
