### PR TITLE
add index.ipynb, change binder paths

### LINKED ISSUE #95: Customize binder startup to show notebook index
If someone uses a standard binder link for this repository (https://mybinder.org/v2/gh/xarray-contrib/xarray-tutorial/HEAD, or the badge in this readme or at https://tutorial.xarray.dev/overview/get-started.html), they end up seeing a rather blank jupyterlab with all the files in this repository.

It would be nice to open an index of notebooks like an index.md with one sentence descriptions like on the planetray computer. (see https://github.com/microsoft/planetary-computer-hub/blob/0d01fd87c016ad142a4b25067455a07c32e053bd/helm/chart/files/etc/singleuser/k8s-lifecycle-hook-post-start.sh)

Even more workspace customization is possible (e.g. automatically open dask labextension or other widgets, multiple notebooks, etc: https://github.com/dask/dask-examples/blob/main/binder/start)

### PR DESCRIPTION
**Pull request by scottyhq**
fixes #95

test on mybinder.org:   https://mybinder.org/v2/gh/scottyhq/xarray-tutorial/index?labpath=workshops/scipy2022/index.ipynb

### CODE REVIEW

**Comment by dcherian** [comment]
Works after I fixed the link. Nice!

I did find a typo, somehow the codespell action didn't catch it
> `indermediate/`

It'd be nice to automate that `index.ipynb`. It seems like a sphinx `toctree` thing. So we could potentially have `index.md` with a sphinx toctree directive and present that: https://myst-nb.readthedocs.io/en/latest/authoring/text-notebooks.html#myst-notebooks-in-jupyter-interfaces

**Comment by scottyhq** [comment]
> I did find a typo, somehow the codespell action didn't catch it

Yeah, codespell definitely does not catch all typos! 

> It'd be nice to automate that index.ipynb

Definitely agree, I'll have a look at how to do that.

>  index.md with a sphinx toctree directive

myst-markdown definitely seems nice, but i'm so used to ipynb! Looks like the numpy tutorial exclusively uses myst-nb https://numpy.org/numpy-tutorials/contributing.html#adding-your-own-tutorials

**Comment by dcherian** [comment]
I wonder if this should instead be the `workshops/scipy-2022/README.md` file rendered as a notebook.

**Comment by scottyhq** [comment]
going to go ahead and merge this as a temporary fix. Could be nice to autogenerate a complete notebook index in the future!

**Pull request merged**
