### PR TITLE
Exercises for the first and second session

### PR DESCRIPTION
**Pull request by keewis**
I noticed that I forgot adding exercises.

Also, let me remind you that since I'm not really a good speaker I won't be doing those sessions myself.

### CODE REVIEW

**Comment by jhamman** [comment]
Hi @keewis - thanks for working on this. I introduced some merge conflicts today (sorry about that).  I will fix them and push to your branch shortly.

**Comment by keewis** [comment]
I noticed and already had them fixed, but then I found a few issues with the formatting and fixed that, too

**Comment by jhamman** [comment]
Ugh. Sorry for crossing wires here @keewis. I think my commit a few minutes ago fixed the final bits. Please take a look to make sure though.

**Comment by keewis** [comment]
sure, and thanks for the final touches. Other than the link style I fixed this looks good to me (the `dask` notebook times out, though)

**Comment by jhamman** [comment]
Thanks @keewis!

**Pull request merged**
