### PR TITLE
Add nbstripout to pre-commit

### PR DESCRIPTION
**Pull request by dcherian**
Implements @zmoon's suggestion to use nbstripout to delete kernel info. 

This builds successfully locally, but asks you to choose a kernel when opening a notebook:
image

### CODE REVIEW

**Comment by scottyhq** [comment]
> This builds successfully locally, but asks you to choose a kernel when opening a notebook: 

I find that kind of annoying and possibly confusing to newcomers. Wish there was a way to simply overwrite kernelname="python3"... 

Is it the case that following instructions here https://github.com/xarray-contrib/xarray-tutorial/blob/main/CONTRIBUTING.md#create-a-python-environment, you'll still end up with the different kernel names if nb_conda_kernels is installed? 

also noting that this PR addresses https://github.com/xarray-contrib/xarray-tutorial/issues/78

**Comment by dcherian** [comment]
AH I just checked.

1. If I run from my `base` environment with `nb-conda-kernels` installed it asks to choose a kernel.
2. If I run from `xarray-tutorial` it just opens up the "default" kernel. I assume this will happen on binder too, but we can triple-check after merging.

Seems like we could recommend tutorial users open `jupyter lab` or `jupyter notebook` in the `xarray-tutorial` environment and then things will work well?

**Comment by scottyhq** [comment]
> I assume this will happen on binder too, but we can triple-check after merging. 

You can just launch binder pointing to this `nbstripout` branch: https://mybinder.org/v2/gh/xarray-contrib/xarray-tutorial/nbstripout?urlpath=lab

**Comment by dcherian** [comment]
image


Sweet got the default kernel on binder.

**Pull request merged**
